language: c
sudo: required
matrix:
  include:
  - os: osx
    osx_image: xcode8
  - os: osx
    osx_image: xcode8.3

before_install:
- 'wget  https://raw.githubusercontent.com/Homebrew/install/master/uninstall'
- chmod +x uninstall
- uninstall -f
#- chmod +x /tmp/uninstall
#- /tmp/uninstall -f
- sudo rm -rf /usr/local/Homebrew || true
- sudo rm -rf /usr/local/Caskroom || true
- sudo rm -rf /usr/local/Cellar || true
- sudo rm -rf /usr/local/bin/brew || true
install:
- sudo easy_install pip
- sudo -H pip install ansible
- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
- ansible-playbook -i tests/inventory tests/test.yml --connection=local
#- 'ansible-playbook -i tests/inventory tests/test.yml --connection=local | grep -q ''changed=-0.*failed=0'' && (echo ''Idempotence test: pass'' && exit 0) || (echo ''Idempotence test: fail'' && exit 1)'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: nT2Vc/6VRtwu7mOLS1O5rKynQz5aZrGpSAZzwtXBhqQ2PjNmOtT/jrr8z/whhf0Wz5VJzU8udijGHQvSzddbN3F+XEiJoq4diDSP5wTRkD58frXhvlteZ2X9jiwseWR3zZ5YwTPPq3Aph7wQitgKPMOTjxlAyj0YxYJzqjaWdpJgE31NOddedArx2FE/XKcXJ2a84gzriQHkZp+oHvViSecS3vrMrFRmMk8WyY/vSLttMfqv2eblH3t0+ZBJBKLm1ojuOASp7jcREBmBdWm0+Rm43p8RH4WIZV+XAv25aVfebAILwU8TJQ/dh1kq8XIycSdrVZQ+AHtvk5pgToWiM3LC/xSAII9Hfi1M5qQYBA1CbM4/N1AaETLpJjsKMUZfzhWDWo/ECHYfsmgSDSB0v6+ApNNESeHG1i2OpILHkdzLOAkdoblocezPAZWyVD85BwQkYzE7CVzEuUnwKjrFf+m2pTWXjXw26vgRaIq9DKmVj3swyfK0LnbEbDzUb4AfXecSviDbbQx4g6as9GRZaoJMnVKhkvyBmtApXi0Xd8S9GMWYxevByovZvtSypQQ6+ZB+fpN07znX55d41FJoF5IvbDy1OzdWQFtNkI17I/Shwe/UmyVAYpk/pglia8n66VuGHaliAWGuyJgc23zH8goCg98MKXjXWM1+33I3dm8=
