---
# tasks file for ansible-brew-file

- name: Test If Homebrew Is Installed
  shell: 'which brew'
  register: brewfile_brew_installed
  failed_when: false
  changed_when: false

- name: Install Homebrew
  shell: '/usr/bin/ruby -e "$(curl -fsSL  https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: brewfile_brew_installed.stdout == ""

- name: Tap rcmdnk/file Homebrew Repo
  homebrew_tap:
    name: rcmdnk/file
    state: present

- name: Install Brew-File
  homebrew:
    name: rcmdnk/file/brew-file
    state: latest
    update_homebrew: yes

- name: Confirm brew-wrap Is In Dotfile
  blockinfile:
    dest: "{{ brewfile_brewwrap_dotfile }}"
    insertafter: EOF
    block: |
      if [ -f $(brew --prefix)/etc/brew-wrap ]; then
        source $(brew --prefix)/etc/brew-wrap
      fi
  when: brewfile_brewwrap_dotfile is defined

- stat: path=~/.brewfile
  register: brewfile_stat

- name: Set brew-file git Repo
  expect:
    command: 'brew-file set_repo -r {{ brewfile_git_repo }} -y'
    responses:
      GitHub password: "{{ brewfile_github_password }}"
  when:
    - brewfile_git_repo is defined
    - brewfile_github_password is defined

- name: Initialize brew-file If First Time
  shell: 'brew file init'
  when:
    - brewfile_new_install == "yes"
    - ( brewfile_stat.stat.isdir is defined and brewfile_stat.stat.isdir )

- name: Install/Update Homebrew Apps from Brewfile
  shell: 'brew file "{{ item }}"'
  with_items:
    - "install --preupdate"
    - "update"
  when: brewfile_new_install == "no"
